### ISSUE TITLE
update package to use latest stylelint version (v13.7.2)

### ISSUE THREAD

**Issue by ademeter** [team23/stylelint-config-team23-scss#1]
When using this package with [latest stylelint-version v13.7.2](https://github.com/stylelint/stylelint/releases/tag/13.7.2) a deprecation-warning is shown like this:
`Deprecation Warning: 'at-rule-blacklist' has been deprecated. Instead use 'at-rule-disallowed-list'. See: https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/at-rule-blacklist/README.md`

**Comment by mmunz** [comment]
@ademeter i updated the scss and standard rules. New Tags are 0.2.x. This also uses newest stylelint and base-configs now.
