### ISSUE TITLE
annotation-no-unknown on !default usage

### ISSUE THREAD

**Issue by erikherberg** [team23/stylelint-config-team23-scss#61]
I currently get an error, if using !default. This seems not to be the correct behavior.

> web/libs/theme/src/lib/theme/variables/_typography.scss
>  13:80  ✖  Unexpected unknown annotation "!default"  annotation-no-unknown

`$font-family-text: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif !default;
`

**Comment by goester-team23** [comment]
I'll look into it.
If this hasn't been fixed in a an upstream dep, we can add !default to be ignored by this rule, as suggested [here](https://github.com/stylelint-scss/stylelint-scss/issues/649#issue-1337106434).

**Comment by goester-team23** [comment]
@herberg-team23 fixed in version [v3.0.1](https://github.com/team23/stylelint-config-team23-scss/releases/tag/v3.0.1)
